spring:
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://121.43.113.188:3306/anymock_opensource?serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 121.43.113.188
    port: 6379

logging:
  pattern:
    console: >
     %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint}
     %clr(${LOG_LEVEL_PATTERN:-%5p})
     %clr(${PID:- }){magenta}
     %clr(---){faint}
     %clr([%15.15t]){faint}
     %clr([%X{mdc_trace_id}]){faint}
     %clr(%-40.40logger{39}){cyan}
     %clr(:){faint} %m${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
    file: >
     %d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}
     ${LOG_LEVEL_PATTERN:-%5p}
     ${PID:- } --- [%t] [%X{mdc_trace_id}] %-40.40logger{39}: %m${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

server:
  port: 8329

anymock:
  core:
    url-prefix: http://127.0.0.1:8330
  manager:
    admin:
      password: A9E62132FE717B74F504A291F96D3F1B

fe:
  pathwin: D:\javacode\AnyMock\anymock-fe\dist\
  pathlin: /root/AnyMock/anymock-fe/dist/